version: "3.9"

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  websocket:
    build: ./websocket-server
    container_name: websocket_server
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  dbdata:
